### ISSUE TITLE
error: Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by magomedikclub1** [XielQs/httptoolkit-pro-patcher#14]
1) Running the first command

```
┌──(user㉿User)-[~/folder/httptoolkits_hack/httptoolkit-pro-patcher]
└─$ sudo npm install 

up to date, audited 43 packages in 554ms

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

2) npm fund

```
┌──(user㉿User)-[~/folder/httptoolkits_hack/httptoolkit-pro-patcher]
└─$ npm fund    
httptoolkit-pro-patcher@1.0.0
├─┬ https://github.com/chalk/chalk?sponsor=1
│ │ └── chalk@4.1.2
│ └── https://github.com/chalk/ansi-styles?sponsor=1
│     └── ansi-styles@4.3.0
├── https://github.com/sponsors/isaacs
│   └── glob@7.2.3
└── https://github.com/chalk/wrap-ansi?sponsor=1
    └── wrap-ansi@7.0.0
```

3) Running the second command

```
┌──(user㉿User)-[~/folder/httptoolkits_hack/httptoolkit-pro-patcher]
└─$ sudo node . patch
[+] HTTP Toolkit found at /opt/HTTP Toolkit
[+] Started patching app...
[+] Extracting app...
[-] An error occurred while extracting app Error: Unable to extract some files:

Error: ENOENT: no such file or directory, open '/opt/HTTP Toolkit/resources/app.asar.unpacked/node_modules/registry-js/build/node_gyp_bins/python3'
    at Object.openSync (node:fs:573:18)
    at Object.readFileSync (node:fs:452:35)
    at Object.readFileSync (/home/folder/httptoolkits_hack/httptoolkit-pro-patcher/node_modules/@electron/asar/lib/disk.js:135:39)
    at Object.extractAll (/home/folder/httptoolkits_hack/httptoolkit-pro-patcher/node_modules/@electron/asar/lib/asar.js:241:38)
    at patchApp (file:///home/folder/httptoolkits_hack/httptoolkit-pro-patcher/index.js:141:10)
    at file:///home/folder/httptoolkits_hack/httptoolkit-pro-patcher/index.js:204:11
    at Object.extractAll (/home/folder/httptoolkits_hack/httptoolkit-pro-patcher/node_modules/@electron/asar/lib/asar.js:253:15)
    at patchApp (file:///home/folder/httptoolkits_hack/httptoolkit-pro-patcher/index.js:141:10)
    at file:///home/folder/httptoolkits_hack/httptoolkit-pro-patcher/index.js:204:11
```
   
4) the necessary file is in the folder

```
$ cd /opt/HTTP\ Toolkit/resources/app.asar.unpacked/node_modules/registry-js/build/node_gyp_bins 

┌──(user㉿User)-[/opt/…/node_modules/registry-js/build/node_gyp_bins]
└─$ ls -lla                
итого 8
drwxr-xr-x 2 root root 4096 фев  2  2024 .
drwxr-xr-x 4 root root 4096 фев  2  2024 ..
lrwxrwxrwx 1 root root   50 янв 19  2024 python3 -> /opt/hostedtoolcache/Python/3.11.7/x64/bin/python3
```

What could be the mistake?
I know python. There is not much JS at all.

**Comment by XielQs** [comment]
can you try using latest version of patcher? (`git pull`)

**Comment by magomedikclub1** [comment]
> can you try using latest version of patcher? (`git pull`)

THANK YOU VERY MUCH!!!
Now life will be better again with an active FREE subscription!
This will save a huge amount of time!
I am very glad!

There is no money for donation now, but I keep in mind that your excellent work is worth paying for!
As soon as the airdrop is issued, I will remember you)
You are the only one who has solved this problem.
And this is already one of the best in this field!

**Comment by XielQs** [comment]
> > can you try using latest version of patcher? (`git pull`)
> 
> THANK YOU VERY MUCH!!!
> Now life will be better again with an active FREE subscription!
> This will save a huge amount of time!
> I am very glad!
> 
> There is no money for donation now, but I keep in mind that your excellent work is worth paying for!
> As soon as the airdrop is issued, I will remember you)
> You are the only one who has solved this problem.
> And this is already one of the best in this field!

Good to see it's working! And I don't need donations, you can donate to the HTTP Toolkit itself instead
