### ISSUE TITLE
 An error occurred while extracting app

### ISSUE THREAD

**Issue by chtowsappx** [XielQs/httptoolkit-pro-patcher#16]
[-] An error occurred while extracting app Error: ENOENT: no such file or directory, lstat 'C:\Users\wsappx\AppData\Local\Temp\httptoolkit-patcher-temp'
    at Object.rmSync (node:fs:1267:13)
    at patchApp (file:///C:/Users/wsappx/Desktop/httptoolkit-pro-patcher/index.js:152:8)
    at file:///C:/Users/wsappx/Desktop/httptoolkit-pro-patcher/index.js:219:11 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'C:\\Users\\wsappx\\AppData\\Local\\Temp\\httptoolkit-patcher-temp'
}

**Comment by XielQs** [comment]
try again with the latest version of patcher
